### ISSUE TITLE
Frequency over 30kHz

### ISSUE THREAD

**Issue by OpaRotbart** [MajicDesigns/MD_AD9833#10]
I can´t set the Frequency over 30kHz, is their a lock in the library that blocks everything over a specific Frequency?

**Comment by MajicDesigns** [comment]
No locks in the library and I can't see anything that would stop this.

Are you using a float for the frequency or a 16 bit integer?

**Comment by OpaRotbart** [comment]
A 16 bit integer at first and now a float, with the float it works, thank you very much for the fast help.
