### ISSUE TITLE
Compiling errors for esp32s3

### ISSUE THREAD

**Issue by Obili69** [MajicDesigns/MD_AD9833#11]
## IMPORTANT
Before submitting this issue
[X] Have you tried using the latest version of the library?
[X] Have you checked this has not already been submitted and/or resolved?
[0] If you are requesting help a better choice may be the [ Arduino forum](http://forum.arduino.cc/)

## Subject of the issue
Describe your issue here.

I get errors while compiling example

## Your Environment
**Library Version: 1.2.2** 
**Arduino IDE version:2.1.1** 
**Hardware model/type: ESP32S3DEV ** 
**OS and Version: Windows 10 22h2** 

## Steps to Reproduce
Explain how to reproduce this issue. Please provide working code below to demonstrate the issue.

Compiling the folowing code

## Expected Behaviour
Explain what should happen.

Succesful Compiling

## Actual Behaviour
Explain what happens instead. Provide log messages if relevant.
C:\Users\cob01\AppData\Local\Temp\.arduinoIDE-unsaved2023710-9084-8c2zpa.xot4\MD_AD9833_Cycle\MD_AD9833_Cycle.ino:13: warning: "FSYNC" redefined
 #define FSYNC 10 ///< SPI Load pin number (FSYNC in AD9833 usage)
c:\Users\cob01\Documents\Arduino\libraries\MD_AD9833\src\MD_AD9833.cpp:282:23: error: 'freq_select' may be used uninitialized in this function [-Werror=maybe-uninitialized]
   spiSend(freq_select | (uint16_t)((_regFreq[chan] >> 14) & 0x3fff));

// Basic MD_AD9833 test file
//
// Initialises the device to default conditions
// 
// Connect a pot to A0 to change the frequency by turning the pot
//
#include <MD_AD9833.h>
#include <SPI.h>

// Pins for SPI comm with the AD9833 IC
#define DATA  11	///< SPI Data pin number
#define CLK   13	///< SPI Clock pin number
#define FSYNC 10	///< SPI Load pin number (FSYNC in AD9833 usage)

MD_AD9833	AD(FSYNC);  // Hardware SPI
// MD_AD9833	AD(DATA, CLK, FSYNC); // Arbitrary SPI pins

#define ARRAY_SIZE(a) (sizeof(a)/sizeof((a)[0]))

void setup(void)
{
  AD.begin();

/*
  AD.setMode(MD_AD9833::MODE_TRIANGLE);
  delay(2000);
  AD.setMode(MD_AD9833::MODE_OFF);
  delay(2000);
  //output is now low
  
  AD.setMode(MD_AD9833::MODE_SINE);
  delay(2000);
  AD.setMode(MD_AD9833::MODE_OFF);
  delay(2000);
  //output is now low

  AD.setMode(MD_AD9833::MODE_SQUARE1);
  delay(2000);
  AD.setMode(MD_AD9833::MODE_OFF);
  delay(2000);
  //output is now high

  AD.setMode(MD_AD9833::MODE_SQUARE2);
  delay(2000);
  AD.setMode(MD_AD9833::MODE_OFF);
  delay(2000);
  //output is now low
*/
}

void loop(void)
{
  static bool bOff = false;
  static uint8_t m = 0;
  static MD_AD9833::mode_t modes[] =
  {
    MD_AD9833::MODE_TRIANGLE,
    MD_AD9833::MODE_SQUARE2,
    MD_AD9833::MODE_SINE,
    MD_AD9833::MODE_SQUARE1
  };

  if (bOff)
    AD.setMode(MD_AD9833::MODE_OFF);
  else
  {
    AD.setMode(modes[m]);
    m++;
    if (m == ARRAY_SIZE(modes)) m = 0;
  }
  bOff = !bOff;
  delay(2000);
}

Insert your code here.
````

**Comment by MajicDesigns** [comment]
Interesting. The compiler is actually incorrect in its assertion of an error. This has happenend for other libraries and the ESP32 compilers.

The parameter 'chan' is an enumerated type that only has values CHAN_1 and CHAN_0. In the function there is a switch case on 'chan' comparing to the 2 values and setting freq_select to a value.

Is the compiler setting -Werror=maybe-uninitialized added by you or is it in the standard package for the ESP hardware?

**Comment by Obili69** [comment]
I used the esp board manager from here:
https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
the installed version is 2.0.11
i use everything in default.

**Comment by Obili69** [comment]
sorry hit the wrong button

**Comment by MajicDesigns** [comment]
OK, I will change the code so that the compiler will not complain with the deafults.

**Comment by MajicDesigns** [comment]
New release v1.2.3 should fix the incorrect compiler errors.

**Comment by Obili69** [comment]
thanks a lot

**Comment by Obili69** [comment]
Works like a charm
