### ISSUE TITLE
Changing the MCLK frequency without changing the .h file

### ISSUE THREAD

**Issue by pe1rmg** [MajicDesigns/MD_AD9833#12]
## IMPORTANT
Before submitting this issue
[X] Have you tried using the latest version of the library?
[X] Have you checked this has not already been submitted and/or resolved?
[X] If you are requesting help a better choice may be the [ Arduino forum](http://forum.arduino.cc/)

## Subject of the issue
I would like to be able to change the clock frequency without changing the .h file for my projects.

## Your Environment
**Library Version:**  1.2.3
**Arduino IDE version:** 2.1.1
**Microcontroller hardware:** RP2040
**OS and Version:** Mac OSX 13.5.1

## Steps to Reproduce
I have low frequency requirements in some projects, therefore I use a 2.5MHz clock instead of the 25MHz clock. To make the calculations correct in my project, I change the MD_AD9833_lib.h file to reflect this.

Would it be possible to change the line 86 to:

#ifndef AD_MCLK
  #define AD_MCLK   25000000UL  ///< Clock speed of the AD9833 reference clock in Hz
#endif

to allow setting the clock frequency in the sketch? Then I do not need to edit the .h file in between projects with different clock frequencies.. Now this edit in the .h file is overwritten during an update of the library.

Thanks!

**Comment by MajicDesigns** [comment]
Changed and released as v1.2.4
