### ISSUE TITLE
Link to MD_cmdProcessor is incorrect

### ISSUE THREAD

**Issue by sdp8483** [MajicDesigns/MD_AD9833#13]
## IMPORTANT
Before submitting this issue
[x] Have you tried using the latest version of the library?
[x] Have you checked this has not already been submitted and/or resolved?
[x] If you are requesting help a better choice may be the [ Arduino forum](http://forum.arduino.cc/)

## Subject of the issue
In the example sketch `MD_AD9833_Test.ino` on line 12 is a comment and link to the required MD_cmdProcessor library. This link is incorrect and points to the repository for MD_AD9833. Correct link address should be: [https://github.com/MajicDesigns/MD_cmdProcessor](https://github.com/MajicDesigns/MD_cmdProcessor)

## Your Environment
**Library Version:** 1.2.4
**Arduino IDE version:** NA
**Microcontroller hardware:** NA
**OS and Version:** NA

## Steps to Reproduce
Open example: [https://github.com/MajicDesigns/MD_AD9833/blob/main/examples/MD_AD9833_Test/MD_AD9833_Test.ino](https://github.com/MajicDesigns/MD_AD9833/blob/main/examples/MD_AD9833_Test/MD_AD9833_Test.ino)

## Expected Behaviour
Link should point to correct library.

## Actual Behaviour
Link points to this library.

## Code Demonstrating the Issue
````
// Dependencies:
// MD_cmdProcessor is available at https://github.com/MajicDesigns/MD_AD9833
//
````

**Comment by MajicDesigns** [comment]
Fixed and update, thanks.
