### ISSUE TITLE
Option to change Master Clock Frequency of AD9833

### ISSUE THREAD

**Issue by michael5411** [MajicDesigns/MD_AD9833#14]
Using this great library in our teaching and blog (art-of-electronics.blog) we changed the entry **`AD_MCLK 25000000UL`** in your library `MD_AD9833_lib.h` to get better resolution for our experiments. This can be done by a Python sketch, but needs recompilation. Quite an ugly way to „solve“ the problem.

Is it possible for you, to provide an easy, more gentle solution, that we can use for our sketches?
We would be really happy to get such a nice new method.

Regards
Mike

**Comment by MajicDesigns** [comment]
Added get/setClk() to set the reference frequency from the application as required. Defaults to AD_MCLK in the library if not set. 

Released as v1.3.0.

**Comment by michael5411** [comment]
Thank you very much!
Excellent improvement!

Regards
Mike

Am Mo., 10. Juni 2024 um 00:18 Uhr schrieb Marco Colli <
***@***.***>:
