### ISSUE TITLE
No Pin Control

### ISSUE THREAD

**Issue by thetechknight** [MajicDesigns/MD_AD9833#6]
This library, just like every other library I have found on this chip, has no ability to enable pin control. the AD9834 can be register controlled (Reset, Phase0/1, Freq0/1) as well as Pin controlled. 

I need the ability to have pin control so I can use a physical chip pin to reset the chip, but more importantly, so I can Phase and Frequency modulate the output from external hardware.

**Comment by MajicDesigns** [comment]
The AD9833 does not have the same pinout as the AD9834. The AD9833 is fully (solely) software controlled. The AD9834 has additional pins to do what you want. As this library is designed to work with  the AD9833 this is not a limitation nor an omission.

However, feel free to take this library and modify to suit your purpose.

**Comment by thetechknight** [comment]
So I get blown off with no love for me or any other person who has this chip then. I see.... Oh well.

**Comment by MajicDesigns** [comment]
Not sure what you expect me to do. I create these libraries for my own projects and make them available to others. I don't need a 9834 library, you do. If you want to modify it feel free. If you want to merge it back in, once you have done so, put up a merge request.
