### ISSUE TITLE
add reset() method

### ISSUE THREAD

**Issue by nwfall** [MajicDesigns/MD_AD9833#7]
I try to build a sweep sine generator with this library and can't find a method to reset the ad9833 chip.
The problem is - when I start the sweep, the phase accumulator of ad9833 is not zero and each new sweep starts from a random phase.
Existing MD_AD9833::begin() method does the job but it is too slow - it takes 220us (which is almost quarter of 1kHz wave).

If there would be a method that triggers the reset bit of ad9833 and works fast it would be great!

**Comment by MajicDesigns** [comment]
Just checking that what you expect the reset to do is just transition the AD9833 reset bit?

**Comment by nwfall** [comment]
Correct, I just want to reset internal phase accumulator of AD9833 to immediately begin the sine sweep loop.

But! I've read some deeper into the datasheet and found that when reset bit held "1" the AD9833 is outputing midscale analog voltage. It could be useful for zeroing dc offset in further analog circuitry.

So maybe it would be more convient to add a parameter to reset method. Something like (excuse my c++):
MD_AD9833::reset(bool r) {
  if(r) set_bit(_ctrl, RESET_BIT);
  else clear_bit(_ctrl, RESET_BIT);
  spi.write(_ctrl);
}

This way there will be even more flexibility.

**Comment by MajicDesigns** [comment]
Added reset() method. Issued as v1.2.0.

**Comment by nwfall** [comment]
Great! Works as expected. The latency now is only 10us. Thank you!
