### ISSUE TITLE
AD9833 Frequency Setting is not atomic

### ISSUE THREAD

**Issue by diyelectromusic** [MajicDesigns/MD_AD9833#8]
## IMPORTANT
Before submitting this issue
[X ] Have you tried using the latest version of the library?
[X ] Have you checked this has not already been submitted and/or resolved?
[X ] If you are requesting help a better choice may be the [ Arduino forum](http://forum.arduino.cc/)

## Subject of the issue
AD9833 Frequency Setting is currently not an atomic operation.

## Your Environment
**Library Version:** 1.2.0
**Arduino IDE version:**  1.8.13
**Hardware model/type:** Arduino Uno and cheap AD9833 module
**OS and Version:** Windows 10

## Steps to Reproduce
Perform a continual sweep of frequency, or derive the value of the frequency from a potentiometer.

## Expected Behaviour
As the input value changes, there should be a smooth transition between frequencies.

## Actual Behaviour
At certain values, there is an audible "click" when changing frequency.

In the function setFrequency, the library states the assumption that B28 is continually set and therefore does not need a control register write to set it every time prior to writing out the two frequency values using spiSend.  However experimentation suggests that this results in a "click" at certain frequencies when attempting to smoothly change the frequency in the audio ranges and viewing the signal on a scope does show discontinuities in the frequency as it changes around certain values.

The datasheet seems somewhat ambiguous on the topic however Figure 28 (the flowchart for a write) does imply that the B28 bit ought to be set for every frequency update to ensure an atomic update.

Adding the line spiSend(_regCtl); prior to the two spiSend calls to update the frequency does seem to remove the click and results in a smooth frequency update which seems to confirm that B28 has to be set for every write.

## Code Demonstrating the Issue
````
void loop () {
    // Assuming a 10k pot on A0
    AD.setFrequency(MD_AD9833::CHAN_0, analogRead(A0));
}
````

**Comment by MajicDesigns** [comment]
Agree with your assessment. Fixed and issued new version 1.2.1.
