### ISSUE TITLE
When switching to MODE_OFF from MODE_SQUARE1, the output stays high

### ISSUE THREAD

**Issue by pstimpel** [MajicDesigns/MD_AD9833#9]
## IMPORTANT
Before submitting this issue
[x] Have you tried using the latest version of the library?
[x] Have you checked this has not already been submitted and/or resolved?
[ ] If you are requesting help a better choice may be the [ Arduino forum](http://forum.arduino.cc/)

## Subject of the issue
When switchiung to MODE_OFF from MODE_SQUARE1, the output stays high. Switching off from all other modes results in the expected low output

## Your Environment
**Library Version:1.2.0** 
**Arduino IDE version:platformio** 
**Hardware model/type:esp32** 
**OS and Version:windows10** 

## Steps to Reproduce
Just turn Square1 on, then off, and check the output

## Expected Behaviour
output should be low after OFF

## Actual Behaviour
output is high, but only after OFF from square1

## Code Demonstrating the Issue
````
AD.setMode(MD_AD9833::MODE_SQUARE1);
delay(1000);
AD.setMode(MD_AD9833::MODE_OFF);
//output is now high

AD.setMode(MD_AD9833::MODE_SQUARE2);
delay(1000);
AD.setMode(MD_AD9833::MODE_OFF);
//output is now low

AD.setMode(MD_AD9833::MODE_TRIANGLE);
delay(1000);
AD.setMode(MD_AD9833::MODE_OFF);
//output is now low

AD.setMode(MD_AD9833::MODE_SINE);
delay(1000);
AD.setMode(MD_AD9833::MODE_OFF);
//output is now low

````

**Comment by MajicDesigns** [comment]
Fixed in release v1.2.2
